version: "3.9"

services:
  database:
    image: postgres:14
    container_name: postgres14-marialuiza
    restart: always
    ports:
      - "${VPN}:${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - pgdata14:/var/lib/postgresql/data

volumes:
  pgdata14:
